# Generated by Django 2.2 on 2020-01-23 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cruduser',
            old_name='ciudad',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='cruduser',
            old_name='ventas',
            new_name='sells',
        ),
    ]
