# Generated by Django 2.2 on 2020-01-23 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200123_2109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cruduser',
            old_name='nombre',
            new_name='name',
        ),
    ]
